-- NOTE: Before execute this commands, execute the "pre data" file located
-- in the current folder to get the database and table which is used below

-- Init
USE [w3resource]
GO

-- Exercise 1
-- Write a SQL query to select all the salespeople. Return salesman_id, name, city,
-- commission with the percent sign (%).

SELECT 
  [salesman_id],
  [name],
  [city],
  [comission]*100 AS [comission],
  '%' AS [sign]
FROM
  [dbo].[salesman]

-- Exercise 2
-- Write a SQL query to find the number of orders booked for each day. Return
-- the result in a format like "For 2001-10-10 there are 15 orders".".

SELECT
  'For',
  [ord_date],
  ', there are',
  COUNT(*) AS [count],
  'orders.'
FROM
  [dbo].[orders]
GROUP BY
  [ord_date]

-- Exercise 3
-- Write a SQL query to find all the orders. Sort the result-set in ascending order
-- by ord_no. Return all fields.

SELECT *
FROM
  [dbo].[orders]
ORDER BY
  [ord_no]

-- Exercise 4
-- Write a SQL query to find all the orders. Sort the result-set in descending
-- order by ord_date. Return all fields.

SELECT *
FROM
  [dbo].[orders]
ORDER BY
  [ord_no] DESC

-- Exercise 5
-- Write a SQL query to find all the orders. Sort the result-set in descending
-- order by ord_date and purch_amt. Return all fields.

SELECT *
FROM
  [dbo].[orders]
ORDER BY
  [ord_date], -- For date descending is from the earlest to the latest 
  [purch_amt] DESC

-- Exercise 6
-- Write a SQL query to find all the customers. Sort the result-set by customer_id.
-- Return cust_name, city, grade.

SELECT
  [cust_name],
  [city],
  [grade]
FROM
  [dbo].[customer]
ORDER BY
  [customer_id]

-- Exercise 7
-- Write a SQL query that calculates the maximum purchase amount generated by each sales
-- person for each order date. Sort the result-set by salesperson id and order date in
-- ascending order. Return salesperson id, order date and maximum purchase amount.

SELECT
  [salesman_id],
  [ord_date],
  MAX(purch_amt) AS [max]
FROM
  [dbo].[orders]
GROUP BY
  [salesman_id],
  [ord_date]
ORDER BY
  [salesman_id],
  [ord_date]

-- Exercise 8
-- Write a SQL query to find all the customers. Sort the result-set in descending
-- order on 3rd field. Return customer name, city and grade.

SELECT
  [cust_name],
  [city],
  [grade]
FROM
  [dbo].[customer]
ORDER BY
  3 DESC  -- 3rd field in SELECT [grade]

-- Exercise 9
-- Write a SQL query that counts the unique orders and the highest purchase amount for
-- each customer. Sort the resultset in descending order on 2nd field. Return customer
-- ID, number of distinct orders and highest purchase amount by each customer.

SELECT
  [customer_id],
  COUNT(*),
  MAX(purch_amt)
FROM
  [dbo].[orders]
GROUP BY
  [customer_id]
ORDER BY

-- Exercise 10
-- Write a SQL query to calculate the summation of purchase amount, total commission
-- (15% for all salespeople) by each order date. Sort the result-set on order date.
-- Return order date, summation of purchase amount and commission.

SELECT
  [ord_date],
  SUM(purch_amt) AS [sum],
  SUM([purch_amt])*0.15 AS [comission]
FROM
  [dbo].[orders]
GROUP BY
  [ord_date]
ORDER BY
  [ord_date]